server:
  port: 8082
  servlet:
    context-path: /app-store

spring:
  application:
    name: app-store
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  datasource:
    url: jdbc:postgresql://...:5433/storage_db
    username: gitecsl
    password: ...
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 10000
  jpa:
    hibernate:
      ddl-auto: update # create, create-drop, validate, none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
samba:
  hots: 134.122.125.240
  share: public
  username: smbuser
  password: ...
  domain:
springdoc:
  swagger-ui:
    path: /swagger-ui.html
